# Generated by Django 3.0.6 on 2020-05-08 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Category Name')),
                ('num_qns_from_cat', models.PositiveIntegerField(default=1, verbose_name='Number of Questions from this Category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_code', models.CharField(max_length=10, verbose_name='Subject Code')),
                ('exam_title', models.CharField(max_length=100, null=True, verbose_name='Exam Title')),
                ('max_marks', models.PositiveIntegerField(default=0)),
                ('show_answer_after_exam', models.BooleanField(default=False, verbose_name='Show answers after the exam?')),
                ('date_closed', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Closing Date and Time')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(max_length=2000, verbose_name='Question')),
                ('figure', models.ImageField(blank=True, null=True, upload_to='questionImages/%Y/%m/%d', verbose_name='Figure')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Category')),
                ('exam', models.ManyToManyField(blank=True, help_text='You can leave it empty if you want to choose random question from a category.', to='exam.Exam', verbose_name='For which Exam?')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['category'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='exam_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.Exam', verbose_name='Exam Name'),
        ),
    ]
