# Generated by Django 3.0.6 on 2020-05-13 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_auto_20200513_1729'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExamTaker',
        ),
    ]
